[package]
name = "geng-derive"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
batbox.workspace = true # TODO: maybe should not be here?

syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
darling.workspace = true

[lib]
proc-macro = true
