[package]
name = "geng"
version = "0.14.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Game Engine"
license = "MIT"
homepage = "https://github.com/kuviman/geng"
edition = "2021"

[features]
default = ["audio"]
audio = ["rodio"]

[dev-dependencies]
gltf = "1"

[dependencies]
batbox = { path = "../batbox", version = "0.14.0" }
geng-derive = { path = "../geng-derive", version = "0.14.0" }
geng-ui-macros = { path = "../geng-ui-macros", version = "0.11.0" }
ugli = { path = "../ugli", version = "0.14.0" }
rusttype = { version = "0.9", features = [ "gpu_cache" ] }
ttf-parser = "0.15"
serde = "1"
lazy_static = "1"
flate2 = "1"
atomic_float = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image = "0.24"
glutin = "0.29"
threadpool = "1"
num_cpus = "1"
notify = "4"
rodio = { git = "https://github.com/RustAudio/rodio", optional = true }
ws = { version = "0.9" }
