[package]
name = "geng"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[features]
default = ["audio"]
audio = ["dep:rodio"]

[dev-dependencies]
gltf.workspace = true

[dependencies]
batbox.workspace = true
geng-derive.workspace = true
geng-ui-macros.workspace = true
ugli.workspace = true

rusttype.workspace = true
ttf-parser.workspace = true
serde.workspace = true
lazy_static.workspace = true
flate2.workspace = true
atomic_float.workspace = true
gilrs.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image.workspace = true
winit.workspace = true
raw-window-handle.workspace = true
glutin-winit.workspace = true
glutin.workspace = true
threadpool.workspace = true
num_cpus.workspace = true
notify.workspace = true
rodio = { workspace = true, optional = true }
ws.workspace = true
